#!/usr/bin/php
<?php

$warning = 70;
$critical = 80;
$domain = "evalentin.ovh";

@require_once (__DIR__ . "/OvhApi.php");
$ovh = new OvhApi(OVH_API_EU, "***", "***", "***");

$list = $ovh->call("GET","/email/domain/$domain/account");

for($i=0;$i<count($list);$i++) {

   $data[$i]['quota'] = $ovh->call("GET","/email/domain/$domain/account/".$list[$i]);
   $data[$i]['usage'] = $ovh->call("GET","/email/domain/$domain/account/".$list[$i]."/usage");
}

$code = 0;

for($i=0;$i<count($data);$i++) {

   $percent = round($data[$i]['usage']->quota * 100 / $data[$i]['quota']->size);

   if($percent > $critical) {
      $code = 2;
      echo $data[$i]['quota']->email . " - " . $data[$i]['usage']->emailCount . " emails - " . $percent . "% used\n";
   }
   else if($percent > $warning) {
      $code = 1;
      echo $data[$i]['quota']->email . " - " . $data[$i]['usage']->emailCount . " emails - " . $percent . "% used\n";
   }
}

exit($code);

?>
